name: vocalx-local

services:
  mongo:
    image: mongo:7
    container_name: vocalx-mongo
    ports:
      - "27017:27017"
    volumes:
      - vocalx_mongo_data:/data/db
    restart: unless-stopped

volumes:
  vocalx_mongo_data:
